version: '3.8'
services:
  cinephile_server: # golang web
    build: server/
    container_name: cinephile_server_dev
    ports: 
      - "4000:4000"
    tty: true
    env_file:
      - ../.env.dev
    volumes:
      - ../src:/cinephile/src
    command: go run main.go 
    # restart: always

  nginx: # loadbalancer
    image: nginx:latest
    container_name: nginx_dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/static/error.html:/etc/nginx/static/error.html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  cinephile_mysql:
    build:
      context: mysql/
    container_name: cinephile_mysql_dev
    env_file:
      - ../.env.dev
    volumes:
      - ./db_volume:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/my.cnf
    ports:
     - '3306:3306'
    command:
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_general_ci
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/var/www/html --email chs29359685@gmail.com --agree-tos --no-eff-email --force-renewal -d api.cinephile.site
    volumes:
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/logs:/var/log/letsencrypt
        - ./certbot/data:/var/www/certbot
  # certbot_t:
  #   depends_on:
  #     - nginx
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/etc:/etc/letsencrypt
  #     - ./certbot/var:/var/lib/letsencrypt
  #     - ./www:/var/www/html
  #   command: certonly --webroot --webroot-path=/var/www/html --email chs29359685@gmail.com --agree-tos --no-eff-email --force-renewal -d api.cinephile.site
  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot:v0.36.0
  #   restart: always
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
